### ISSUE TITLE
automatically lint ansible code

### ISSUE THREAD

**Issue by rmkraus** [project-faros/cluster-manager#13]
Reference:

https://www.ansible.com/blog/ansible-linting-with-github-actions

**Comment by mulbc** [comment]
I added a pre-commit config and a Github Action in my [new branch linting](https://github.com/project-faros/cluster-manager/tree/linting)
I also made sure that I make the necessary changes to have all linters happy. @rmkraus  could you please run these playbooks from the branch so that we can ensure they still work as expected? Then we can merge this and see if the GH Action works as well :)
