### ISSUE TITLE
enable the registry

### ISSUE THREAD

**Issue by rmkraus** [project-faros/cluster-manager#28]
```
farosctl oc patch configs.imageregistry.operator.openshift.io cluster --type merge --patch '{"spec":{"storage":{"pvc":{"claim":""}}}}'
farosctl oc patch configs.imageregistry.operator.openshift.io/cluster --type merge -p '{"spec":{"managementState":"Managed"}}'
```

**Comment by rmkraus** [comment]
a default storage class must be set first.

**Comment by mulbc** [comment]
@rmkraus has this ever been solved? I can't find any code for `imageregistry` and there are no commits associated with this issue

**Comment by rmkraus** [comment]
Yes, this was resolved in the docs: https://faros.dev/storage.html#enable-cluster-registry

Do you think this should be somewhere else? The main reason I hadn't put this in the storage install script is because I don't want to programatically wait for storage to be available. Then again, there really isn't a need to wait as k8s will simply create the pv when the storageclass becomes available. 

What do you think?

**Comment by mulbc** [comment]
As a customer I would expect my OpenShift cluster to come with a working Registry. By default we cannot offer this on Bare Metal, since we don't know if a suitable storage is available.
For Faros, we do know that a suitable Storage is available, since we make sure to install it - so IMO we should enable the registry after the storage is installed.
We unfortuantely cannot just configure the registry and let it retry once storage is installed, since the PVCs would be stuck (if created before the provisioner / storage class is there). So we will have to first install ODF, then configure the Registry

**Comment by rmkraus** [comment]
Relevant: https://stackoverflow.com/questions/57433963/ansible-kubernetes-how-to-wait-for-a-job-completion
