### ISSUE TITLE
named gets configured to listen on external ip and localhost, but not internal

### ISSUE THREAD

**Issue by kjw3** [project-faros/cluster-manager#67]
named service is listening on external ip and 127.0.0.1 on the bastion.

However, the rhcos nodes are set to use the internal ip of the bastion for DNS. Thus the bootstrap machine cannot pull images to start the process.

```
#before:
options {
    listen-on           port 53 { 192.168.8.1; 127.0.0.1; };
----------
#after manual change:
options {
    listen-on           port 53 { 192.168.8.1; 192.168.1.1; 127.0.0.1; };

#restart named
$ sudo systemctl restart named
```

**Comment by rmkraus** [comment]
Confirmed. 

The issue is here: https://github.com/project-faros/cluster-manager/blob/master/app/playbooks/apply.d/router/create_router.yml#L22

The variable `dns_server_ip` is not defined so its default value is used. The default is 192.168.8.1. The fact that this IP address matches your WAN interface is actually just a happy accident.
